@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@path = http://{{host}}/stripe/

GET {{path}}setup
###
POST {{path}}customer/create
content-type: application/json

{
  "email": "ilkka.salmenius@gmail.com",
  "name": "Ilkka Salmenius",
  "phone": "050 61698"
}
###
DELETE {{path}}customer/delete/cus_GijwasXiJdNazm
###
POST {{path}}create-payment-method
content-type: application/json

{
  "name": "Ilkka Salmenius",
  "email": "ilkka.salmenius@gmail.com",
  "phone": "050 61698",
  "number": "4242 4242 4242 4242",
  "expMonth": 12,
  "expYear": 22,
  "cvc": "123"
}
###
POST {{path}}create-payment-intent
content-type: application/json

{
  "amount": 295,
  "currency": "eur"
}

